/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.AdministradorArray;
import Control.AdmitirSupers;
import Model.Persona;
import javax.swing.JOptionPane;
import Model.SuperHumanos;

/**
 *
 * @author Juan José
 */
public class FRM_Principal extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Principal
     */
    AdministradorArray administradorArray;
    AdmitirSupers admitirSupers;
    public FRM_Principal() {
        initComponents();
        administradorArray=new AdministradorArray();
        administradorArray.CrearArraylist();
        admitirSupers=new AdmitirSupers();
        admitirSupers.CrearArraylist2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        btn_IngresarDatos = new javax.swing.JButton();
        btn_Imprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_Reporte = new javax.swing.JTextArea();
        btn_GenerateSupers = new javax.swing.JButton();
        humanos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta_supers = new javax.swing.JTextArea();
        superhumans = new javax.swing.JLabel();
        btn_CrearSupers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_IngresarDatos.setText("Ingresar Datos");
        btn_IngresarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarDatosActionPerformed(evt);
            }
        });

        btn_Imprimir.setText("Imprimir Humanos");
        btn_Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImprimirActionPerformed(evt);
            }
        });

        jta_Reporte.setColumns(20);
        jta_Reporte.setRows(5);
        jScrollPane1.setViewportView(jta_Reporte);

        btn_GenerateSupers.setText("Generar super Humanos");
        btn_GenerateSupers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GenerateSupersActionPerformed(evt);
            }
        });

        humanos.setText("Humanos");

        jta_supers.setColumns(20);
        jta_supers.setRows(5);
        jScrollPane2.setViewportView(jta_supers);

        superhumans.setText("SuperHumanos");

        btn_CrearSupers.setText("Crear SuperHumanos");
        btn_CrearSupers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearSupersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(humanos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(superhumans, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btn_IngresarDatos)
                .addGap(18, 18, 18)
                .addComponent(btn_Imprimir)
                .addGap(18, 18, 18)
                .addComponent(btn_CrearSupers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_GenerateSupers)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_IngresarDatos)
                    .addComponent(btn_Imprimir)
                    .addComponent(btn_GenerateSupers)
                    .addComponent(btn_CrearSupers))
                .addGap(29, 29, 29)
                .addComponent(humanos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(superhumans)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IngresarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarDatosActionPerformed
        String nombre=JOptionPane.showInputDialog("Ingrese su nombre");
        String edad=JOptionPane.showInputDialog("Ingrese su edad");
        String estadoCivil=JOptionPane.showInputDialog("Ingrese su estado civil");
        String DNI=JOptionPane.showInputDialog("Ingrese su DNI");
        String CiudadDeResidencia=JOptionPane.showInputDialog("Ingrese su Ciudad de residencia");
        Persona persona=new Persona(nombre,edad,estadoCivil,DNI,CiudadDeResidencia);
        administradorArray.InsertarPersona(persona);
        JOptionPane.showMessageDialog(null, "Persona Guardada Correctamente");
    }//GEN-LAST:event_btn_IngresarDatosActionPerformed

    private void btn_ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImprimirActionPerformed
        jta_Reporte.setText("");
        jta_Reporte.setText(administradorArray.DevolverInformacion());
    }//GEN-LAST:event_btn_ImprimirActionPerformed

    private void btn_GenerateSupersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GenerateSupersActionPerformed
        jta_supers.setText("");
        //jta_supers.setText(SuperHumanos.poderXray);
    }//GEN-LAST:event_btn_GenerateSupersActionPerformed

    private void btn_CrearSupersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearSupersActionPerformed
        String SuperNombre=JOptionPane.showInputDialog("Ingrese su nombre");
        String SaludMental=JOptionPane.showInputDialog("Ingrese su edad");
        String superFuerza=JOptionPane.showInputDialog("Ingrese su estado civil");
        String visionLaser=JOptionPane.showInputDialog("Ingrese su DNI");
        String visionXray=JOptionPane.showInputDialog("Ingrese su Ciudad de residencia");
        Persona superh=new SuperHumanos(nombre,edad,estadoCivil,DNI,CiudadDeResidencia,
                SuperNombre,SaludMental,superFuerza,visionLaser,visionXray);
        admitirSupers.InsertarSuper(superh);
        JOptionPane.showMessageDialog(null, "SuperHumano Guardado Correctamente");
    }//GEN-LAST:event_btn_CrearSupersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CrearSupers;
    private javax.swing.JButton btn_GenerateSupers;
    private javax.swing.JButton btn_Imprimir;
    private javax.swing.JButton btn_IngresarDatos;
    private javax.swing.JLabel humanos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jta_Reporte;
    private javax.swing.JTextArea jta_supers;
    private javax.swing.JLabel superhumans;
    // End of variables declaration//GEN-END:variables
}
