/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.AdministradorArray;
import Control.AdmitirSupers;
import Model.Persona;
import javax.swing.JOptionPane;
import Model.SuperHumanos;

/**
 *
 * @author Juan José
 */
public class FRM_Principal extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Principal
     */
    AdministradorArray administradorArray;
    AdmitirSupers admitirSupers;
    public FRM_Principal() {
        initComponents();
        administradorArray=new AdministradorArray();
        administradorArray.CrearArraylist();
        admitirSupers=new AdmitirSupers();
        admitirSupers.CrearArraylist2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        btn_IngresarDatos = new javax.swing.JButton();
        btn_ImprimirDatos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_Reporte = new javax.swing.JTextArea();
        btn_ImprimirSuperHumanosA = new javax.swing.JButton();
        humanos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta_superhumanosA = new javax.swing.JTextArea();
        superhumans = new javax.swing.JLabel();
        btn_CrearSuperHumanos = new javax.swing.JButton();
        btn_ImprimirSuperHumanosD = new javax.swing.JButton();
        btn_CrearEscuadronesSH = new javax.swing.JButton();
        btn_IngresarDatosAlfis = new javax.swing.JButton();
        btn_EmpezarGuerra = new javax.swing.JButton();
        btn_ImprimirDatosAlfis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jta_superhumanosD = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btn_ImprimirEscuadron1 = new javax.swing.JButton();
        btn_ImprimirEscuadron2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jta_ImprimirEscuadron1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_IngresarDatos.setText("Ingresar Humanos");
        btn_IngresarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarDatosActionPerformed(evt);
            }
        });

        btn_ImprimirDatos.setText("Imprimir Humanos");
        btn_ImprimirDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImprimirDatosActionPerformed(evt);
            }
        });

        jta_Reporte.setColumns(20);
        jta_Reporte.setRows(5);
        jScrollPane1.setViewportView(jta_Reporte);

        btn_ImprimirSuperHumanosA.setText("Imprimir SuperHumanos admitidos");
        btn_ImprimirSuperHumanosA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImprimirSuperHumanosAActionPerformed(evt);
            }
        });

        humanos.setText("Humanos");

        jta_superhumanosA.setColumns(20);
        jta_superhumanosA.setRows(5);
        jScrollPane2.setViewportView(jta_superhumanosA);

        superhumans.setText("SuperHumanos Admitidos");

        btn_CrearSuperHumanos.setText("Pruebas SuperHumanos");
        btn_CrearSuperHumanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearSuperHumanosActionPerformed(evt);
            }
        });

        btn_ImprimirSuperHumanosD.setText("Imprimir SuperHumanos denegados");
        btn_ImprimirSuperHumanosD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImprimirSuperHumanosDActionPerformed(evt);
            }
        });

        btn_CrearEscuadronesSH.setText("Conformar Escuadrones");
        btn_CrearEscuadronesSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearEscuadronesSHActionPerformed(evt);
            }
        });

        btn_IngresarDatosAlfis.setText("Llegada de ALFIS");
        btn_IngresarDatosAlfis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarDatosAlfisActionPerformed(evt);
            }
        });

        btn_EmpezarGuerra.setText("GUERRA");
        btn_EmpezarGuerra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EmpezarGuerraActionPerformed(evt);
            }
        });

        btn_ImprimirDatosAlfis.setText("Imprimir Alfis");
        btn_ImprimirDatosAlfis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImprimirDatosAlfisActionPerformed(evt);
            }
        });

        jLabel1.setText("SuperHumanos Denegados");

        jta_superhumanosD.setColumns(20);
        jta_superhumanosD.setRows(5);
        jScrollPane3.setViewportView(jta_superhumanosD);

        jLabel2.setText("Imprimir Escuadron 1 SuperHumanos");

        btn_ImprimirEscuadron1.setText("Imprimir Escuadron 1");
        btn_ImprimirEscuadron1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImprimirEscuadron1ActionPerformed(evt);
            }
        });

        btn_ImprimirEscuadron2.setText("Imprimir Escuadron 2");
        btn_ImprimirEscuadron2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImprimirEscuadron2ActionPerformed(evt);
            }
        });

        jta_ImprimirEscuadron1.setColumns(20);
        jta_ImprimirEscuadron1.setRows(5);
        jScrollPane4.setViewportView(jta_ImprimirEscuadron1);

        jLabel3.setText("Imprimir ALFIS");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane5.setViewportView(jTextArea3);

        jLabel4.setText("Imprimir Escuadron 2 SuperHumanos");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane6.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(superhumans, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(humanos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_CrearEscuadronesSH)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ImprimirEscuadron1)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ImprimirEscuadron2)
                                .addGap(18, 18, 18)
                                .addComponent(btn_IngresarDatosAlfis)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ImprimirDatosAlfis, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btn_EmpezarGuerra, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_IngresarDatos)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ImprimirDatos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_CrearSuperHumanos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ImprimirSuperHumanosA)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ImprimirSuperHumanosD)))
                        .addContainerGap(98, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_IngresarDatos)
                    .addComponent(btn_ImprimirDatos)
                    .addComponent(btn_ImprimirSuperHumanosA)
                    .addComponent(btn_CrearSuperHumanos)
                    .addComponent(btn_ImprimirSuperHumanosD))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_EmpezarGuerra, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CrearEscuadronesSH)
                    .addComponent(btn_ImprimirEscuadron1)
                    .addComponent(btn_ImprimirEscuadron2)
                    .addComponent(btn_IngresarDatosAlfis)
                    .addComponent(btn_ImprimirDatosAlfis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(humanos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(superhumans)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IngresarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarDatosActionPerformed
        String nombre=JOptionPane.showInputDialog("Ingrese su nombre");
        String edad=JOptionPane.showInputDialog("Ingrese su edad");
        String estadoCivil=JOptionPane.showInputDialog("Ingrese su estado civil");
        String DNI=JOptionPane.showInputDialog("Ingrese su DNI");
        String CiudadDeResidencia=JOptionPane.showInputDialog("Ingrese su Ciudad de residencia");
        String Hijos=JOptionPane.showInputDialog("¿Cuantos hij@s tiene?");
        Persona persona=new Persona(nombre,edad,estadoCivil,DNI,CiudadDeResidencia, Hijos);
        administradorArray.InsertarPersona(persona);
        JOptionPane.showMessageDialog(null, "Persona Guardada Correctamente");
    }//GEN-LAST:event_btn_IngresarDatosActionPerformed

    private void btn_ImprimirDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImprimirDatosActionPerformed
        jta_Reporte.setText("");
        jta_Reporte.setText(administradorArray.DevolverInformacion());
    }//GEN-LAST:event_btn_ImprimirDatosActionPerformed

    private void btn_ImprimirSuperHumanosAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImprimirSuperHumanosAActionPerformed
        jta_superhumanosA.setText("");
        //jta_supers.setText(SuperHumanos.poderXray);
    }//GEN-LAST:event_btn_ImprimirSuperHumanosAActionPerformed

    private void btn_CrearSuperHumanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearSuperHumanosActionPerformed
        String superFuerza =JOptionPane.showInputDialog("Ingrese su nombre");
        String visionLaser =JOptionPane.showInputDialog("Ingrese su nombre");
        String visionXray =JOptionPane.showInputDialog("Ingrese su nombre");
        SuperHumanos superh = new SuperHumanos(nombre,edad,estadoCivil,DNI,CiudadDeResidencia, Hijos, 
                superFuerza,visionLaser,visionXray);
        admitirSupers.InsertarSuper(superh);
        JOptionPane.showMessageDialog(null, "SuperHumano Guardado Correctamente");
    }//GEN-LAST:event_btn_CrearSuperHumanosActionPerformed

    private void btn_IngresarDatosAlfisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarDatosAlfisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_IngresarDatosAlfisActionPerformed

    private void btn_ImprimirDatosAlfisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImprimirDatosAlfisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ImprimirDatosAlfisActionPerformed

    private void btn_ImprimirSuperHumanosDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImprimirSuperHumanosDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ImprimirSuperHumanosDActionPerformed

    private void btn_CrearEscuadronesSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearEscuadronesSHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CrearEscuadronesSHActionPerformed

    private void btn_EmpezarGuerraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EmpezarGuerraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_EmpezarGuerraActionPerformed

    private void btn_ImprimirEscuadron1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImprimirEscuadron1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ImprimirEscuadron1ActionPerformed

    private void btn_ImprimirEscuadron2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImprimirEscuadron2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ImprimirEscuadron2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CrearEscuadronesSH;
    public javax.swing.JButton btn_CrearSuperHumanos;
    private javax.swing.JButton btn_EmpezarGuerra;
    public javax.swing.JButton btn_ImprimirDatos;
    private javax.swing.JButton btn_ImprimirDatosAlfis;
    private javax.swing.JButton btn_ImprimirEscuadron1;
    private javax.swing.JButton btn_ImprimirEscuadron2;
    public javax.swing.JButton btn_ImprimirSuperHumanosA;
    private javax.swing.JButton btn_ImprimirSuperHumanosD;
    public javax.swing.JButton btn_IngresarDatos;
    private javax.swing.JButton btn_IngresarDatosAlfis;
    private javax.swing.JLabel humanos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jta_ImprimirEscuadron1;
    public javax.swing.JTextArea jta_Reporte;
    public javax.swing.JTextArea jta_superhumanosA;
    private javax.swing.JTextArea jta_superhumanosD;
    private javax.swing.JLabel superhumans;
    // End of variables declaration//GEN-END:variables
}
